### ISSUE TITLE
As a user, I want to remove the legacy CSV

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#541]
Given that the legacy CSV is deprecated for removal
When I consider the upcoming breaking changes to include in 7.0
Then I want to provide users with notice that this option will be removed and then remove it

**Comment by epag** [comment]
Ended up using a GUI tool called panoply to open the Netcdf files and the outputs produced by scenario512 and scenario650 looked identical so I believe we should be good with manual testing

**Comment by epag** [comment]
Working on this next

**Comment by epag** [comment]
Nice, looks like I thought ahead when externalizing our writer/readers and never moved Legacy CSV or netcdf over there so that should mean it will be an easier clean up

**Comment by james-d-brown** [comment]
Yes, that is the bulk of the effort, unfortunately, and it is painstaking/tedious because every legacy benchmark will need to be correlated with the new benchmark. It is easy for the small tests, much harder for the large ones.

**Comment by epag** [comment]
Hm, not sure how we currently handle this with pairs, but it seems by default that we are gzip'ing csv2 responses. If we want a true pairity of comparison then we would need to unzip this response to actually compare the results.

**Comment by epag** [comment]
> I suppose it depends what you mean by handle.
> 
> Each format (other than netcdf) is unit tested, which means that there are a number of fixed expectations against which assertions are made. In other words, files are written (to an in-memory store), then read back in and assertions are made against them.
> 
> There is no need to formally unit test any kind of comparison between formats because each format has its own unit tests.
> 
> I think what we're aiming to do here is just to make sure that the updated (csv2) benchmarks for the system tests are consistent with the old (csv) benchmarks. Again, the csv2 format is unit tested for correctness, but is generally advisable to take extra precautions when swapping out system test benchmarks because these are being used - forevermore - to assert accuracy of the software at the very top level of integration, i.e., there is a very high bar for accuracy of these benchmarks. To create them in the first place, we went through pretty rigorous checks, including against other software.
> 
> Whether the csv2 is zipped or not zipped doesn't really matter in this context because any checks will be manual. Yes, you will need to unzip them to manually inspect them (whether by hand or script). Does that help?

Yeah that makes sense, I thought the systests did a level of automated comparison beyond checking that the expected output files were created. If the checking is mostly manual then I believe that answers my question

**Comment by james-d-brown** [comment]
No, they are very different and the csv2 contains *way* more metadata.

**Comment by epag** [comment]
Fully checked the CSV produced from scenario720 and results are consistent between legacy csv and csv2

**Comment by epag** [comment]
I am around ~1/3rd done updating all the scenario tests. I have time cut out tomorrow to wrap this work up

**Comment by epag** [comment]
I may have actually found it

```
# importing pandas package 
import pandas as pandasForSortingCSV 
  
# assign dataset 
csvData = pandasForSortingCSV.read_csv("evaluation_staging.csv") 
file1 = open("stageSort.txt", "w") 
                                         
# displaying unsorted data frame 
print("\nBefore sorting:") 
print(csvData) 
  
# sort data frame 
csvData.sort_values(["POOL NUMBER"],  
                    axis=0, 
                    ascending=[False],  
                    inplace=True) 
  
# displaying sorted data frame 
print("\nAfter sorting:") 
print(csvData) 

file1.write(csvData.to_string())

file1.close()
```

**Comment by james-d-brown** [comment]
You don't need a script, just a one-liner in unix/linux. 

You will need to check the column numbers, though, as they may have changed:

`(head -n 1 evaluation.csv && tail -n +2 evaluation.csv | sort -t, -k5n,5 -k53n,53 ) > sorted_evaluation.csv`

You want to sort by pool number and statistics group number.

**Comment by epag** [comment]
I changed the ScenarioHelper to no longer worry about sorting and instead is doing this:

```
assertThat(expectedRows).contains(actualRows.get( i ).trim());
```

**Comment by epag** [comment]
It is consistent between runs of the same build, but if I rebuild then we get failures introduced

**Comment by epag** [comment]
So just to summarize:

- I should create a ticket for the group number thing that I discovered above (And that will block this ticket till it is resolved?)
- I can meet with Hank to validate the additional data that was added to the csv2 benchmark files

**Comment by james-d-brown** [comment]
( There are actually a bunch of tests that do not have statistics benchmarks. )

**Comment by epag** [comment]
> Oh, I guess there was one more thing, why scenario409 is failing as it doesn't (shouldn't) have statistics benchmarks...

Here is the diff between the failing line for scenario 409

<img width="2199" height="435" alt="Image" src="https://github.com/user-attachments/assets/0e546248-6882-4ad1-a99f-854c5ca33f3d" />


Here is the header as well:
```
OBSERVED VARIABLE NAME,PREDICTED VARIABLE NAME,BASELINE VARIABLE NAME,COVARIATE FILTERS,POOL NUMBER,EVALUATION SUBJECT,FEATURE GROUP NAME,OBSERVED FEATURE NAME,OBSERVED FEATURE WKT,OBSERVED FEATURE SRID,OBSERVED FEATURE DESCRIPTION,PREDICTED FEATURE NAME,PREDICTED FEATURE WKT,PREDICTED FEATURE SRID,PREDICTED FEATURE DESCRIPTION,BASELINE FEATURE NAME,BASELINE FEATURE WKT,BASELINE FEATURE SRID,BASELINE FEATURE DESCRIPTION,EARLIEST ISSUED TIME EXCLUSIVE,LATEST ISSUED TIME INCLUSIVE,EARLIEST VALID TIME EXCLUSIVE,LATEST VALID TIME INCLUSIVE,EARLIEST LEAD DURATION EXCLUSIVE,LATEST LEAD DURATION INCLUSIVE,TIME SCALE DURATION,TIME SCALE FUNCTION,TIME SCALE START MONTH-DAY INCLUSIVE,TIME SCALE END MONTH-DAY INCLUSIVE,EVENT THRESHOLD NAME,EVENT THRESHOLD LOWER VALUE,EVENT THRESHOLD UPPER VALUE,EVENT THRESHOLD UNITS,EVENT THRESHOLD LOWER PROBABILITY,EVENT THRESHOLD UPPER PROBABILITY,EVENT THRESHOLD SIDE,EVENT THRESHOLD OPERATOR,DECISION THRESHOLD NAME,DECISION THRESHOLD LOWER VALUE,DECISION THRESHOLD UPPER VALUE,DECISION THRESHOLD UNITS,DECISION THRESHOLD LOWER PROBABILITY,DECISION THRESHOLD UPPER PROBABILITY,DECISION THRESHOLD SIDE,DECISION THRESHOLD OPERATOR,METRIC NAME,METRIC COMPONENT NAME,METRIC COMPONENT QUALIFIER,METRIC COMPONENT UNITS,METRIC COMPONENT MINIMUM,METRIC COMPONENT MAXIMUM,METRIC COMPONENT OPTIMUM,STATISTIC GROUP NUMBER,SUMMARY STATISTIC NAME,SUMMARY STATISTIC COMPONENT NAME,SUMMARY STATISTIC UNITS,SUMMARY STATISTIC DIMENSIONS,SUMMARY STATISTIC QUANTILE,SAMPLE QUANTILE,STATISTIC
```

**Comment by epag** [comment]
The branch has around 1000 files changed so I think it just got swept up in my changes

**Comment by HankHerr-NOAA** [comment]
Using the code from the branch, I believe that these are the three tests that are still failing:

```
wres.systests.SystemTestSuite > wres.systests.Scenario400.testScenario FAILED
    junit.framework.AssertionFailedError at Scenario400.java:124

wres.systests.SystemTestSuite > wres.systests.Scenario102.testScenario FAILED
    junit.framework.AssertionFailedError at Scenario102.java:82

wres.systests.SystemTestSuite > wres.systests.Scenario100.testScenario FAILED
    junit.framework.AssertionFailedError at Scenario100.java:128
```

All three include benchmarks for the legacy CSV. So there are no new statistics to confirm. Please confirm, Evan, if these are the three tests you expect to fail. I'm assuming these fall under the new #575 ticket, correct?

Thanks,

Hank

**Comment by james-d-brown** [comment]
Hank, that is not correct.

As noted above, any evaluation that fails to declare `metrics` (all of evaluations mentioned above, for example) and contains legacy CSV benchmarks (all of the evaluations mentioned above, for example) WILL have new statistics to confirm because several metrics have been added that are supported by csv2 and NOT by the legacy csv.

**Comment by HankHerr-NOAA** [comment]
Oh. Got it. Then I'll have to check the evaluation CSVs to see what metrics are included that were not in the old benchmarks and then determine how to check those results. 

In my second run of the system tests, I now see the failures for scenario1000 and 1001, which I believe are due to time series metrics and should be addressed with #575.

More in the meeting,

Hank

**Comment by james-d-brown** [comment]
Yeah, this is the unfortunate side-effect of having system tests that are moving targets, aka "all valid" metrics, or with no `metrics` declaration in the new schema. It is nice for users to have the option not to declare metrics, but it has been a longstanding PITA for us. I suppose we could minimize the number of tests without `metrics` declaration, but we'll always need one or two.

**Comment by HankHerr-NOAA** [comment]
The following evaluations do NOT declare the `metrics` explicitly:

```
scenario100/evaluation.yml
scenario102/evaluation.yml
scenario400/evaluation.yml
scenario900_long/evaluation.yml
scenario901_noclean/evaluation.yml
scenario902_long/evaluation.yml
scenario910_long/evaluation.yml
scenario911_long/evaluation.yml
scenario912_long/evaluation.yml
```

The 900 series is not benchmarked; rather, a list of expected outputs is included. That list does include the legacy CSVs and needs to be updated. 

*Evan: Do you have time to update the dirListing.txt files stored in the 900-series benchmarks directory?* If not, I can do that as part of this work. I think its just a matter of removing the .csvs from the directory listing and then running the tests to confirm. 

I'm going to look at the 100, 102, and 400 scenarios now.

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Does anyone know how to cross reference a folder under `systests/output` with a specific scenario when all system tests are executed? 

Hank

**Comment by HankHerr-NOAA** [comment]
I found it... Here is an example for scenario303:

```
test-results/test/TEST-wres.systests.Scenario303.xml:2025-07-31T15:50:46.875+0000  [Test worker] INFO Evaluator - Wrote the following output: [/omimtted/git/wres/systests/build/install/systests/./outputs/wres_evaluation_0cTjU7dbpiecAoh-JFWXxxJTzWA/evaluation.csv.gz, /omitted/git/wres/systests/build/install/systests/./outputs/wres_evaluation_0cTjU7dbpiecAoh-JFWXxxJTzWA/evaluation.csvt, /omitted/git/wres/systests/build/install/systests/./outputs/wres_evaluation_0cTjU7dbpiecAoh-JFWXxxJTzWA/pairs.csv.gz]
```

Its XML files in `test-results/test`,

Hank

**Comment by HankHerr-NOAA** [comment]
Looking at the results for `scenario100`... Here is what we benchmarked before:

```
LGNN5_LGNN5_HEFS_BIAS_FRACTION.csv
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_ERRORS_BY_FORECAST_VALUE_151200_SECONDS.csv
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_ERRORS_BY_OBSERVED_VALUE_151200_SECONDS.csv
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_ERRORS.csv
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_PERCENTAGE_ERRORS.csv
LGNN5_LGNN5_HEFS_BRIER_SCORE.csv
LGNN5_LGNN5_HEFS_BRIER_SKILL_SCORE.csv
LGNN5_LGNN5_HEFS_COEFFICIENT_OF_DETERMINATION.csv
LGNN5_LGNN5_HEFS_CONTINUOUS_RANKED_PROBABILITY_SCORE.csv
LGNN5_LGNN5_HEFS_INDEX_OF_AGREEMENT.csv
LGNN5_LGNN5_HEFS_KLING_GUPTA_EFFICIENCY.csv
LGNN5_LGNN5_HEFS_MEAN_ABSOLUTE_ERROR.csv
LGNN5_LGNN5_HEFS_MEAN_ERROR.csv
LGNN5_LGNN5_HEFS_MEAN_SQUARE_ERROR.csv
LGNN5_LGNN5_HEFS_MEAN_SQUARE_ERROR_SKILL_SCORE.csv
LGNN5_LGNN5_HEFS_PEARSON_CORRELATION_COEFFICIENT.csv
LGNN5_LGNN5_HEFS_QUANTILE_QUANTILE_DIAGRAM_151200_SECONDS.csv
LGNN5_LGNN5_HEFS_RELATIVE_OPERATING_CHARACTERISTIC_DIAGRAM_151200_SECONDS.csv
LGNN5_LGNN5_HEFS_RELATIVE_OPERATING_CHARACTERISTIC_SCORE.csv
LGNN5_LGNN5_HEFS_RELIABILITY_DIAGRAM_151200_SECONDS.csv
LGNN5_LGNN5_HEFS_ROOT_MEAN_SQUARE_ERROR.csv
LGNN5_LGNN5_HEFS_SAMPLE_SIZE.csv
LGNN5_LGNN5_HEFS_SUM_OF_SQUARE_ERROR.csv
LGNN5_LGNN5_HEFS_VOLUMETRIC_EFFICIENCY.csv
sorted_pairs.csv
```

Here is the output from the evaluation:

```
evaluation.csv.gz
evaluation.csvt
LGNN5_LGNN5_HEFS_BIAS_FRACTION.png
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_ERRORS_BY_FORECAST_VALUE_151200_SECONDS.png
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_ERRORS_BY_OBSERVED_VALUE_151200_SECONDS.png
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_ERRORS.png
LGNN5_LGNN5_HEFS_BOX_PLOT_OF_PERCENTAGE_ERRORS.png
LGNN5_LGNN5_HEFS_BRIER_SCORE.png
LGNN5_LGNN5_HEFS_BRIER_SKILL_SCORE.png
LGNN5_LGNN5_HEFS_COEFFICIENT_OF_DETERMINATION.png
LGNN5_LGNN5_HEFS_CONTINUOUS_RANKED_PROBABILITY_SCORE.png
LGNN5_LGNN5_HEFS_ENSEMBLE_QUANTILE_QUANTILE_DIAGRAM_151200_SECONDS.png
LGNN5_LGNN5_HEFS_EQUITABLE_THREAT_SCORE.png
LGNN5_LGNN5_HEFS_FALSE_ALARM_RATIO.png
LGNN5_LGNN5_HEFS_FREQUENCY_BIAS.png
LGNN5_LGNN5_HEFS_INDEX_OF_AGREEMENT.png
LGNN5_LGNN5_HEFS_KLING_GUPTA_EFFICIENCY.png
LGNN5_LGNN5_HEFS_MAXIMUM_LEFT.png
LGNN5_LGNN5_HEFS_MAXIMUM_RIGHT.png
LGNN5_LGNN5_HEFS_MEAN_ABSOLUTE_ERROR.png
LGNN5_LGNN5_HEFS_MEAN_ABSOLUTE_ERROR_SKILL_SCORE.png
LGNN5_LGNN5_HEFS_MEAN_ERROR.png
LGNN5_LGNN5_HEFS_MEAN_LEFT.png
LGNN5_LGNN5_HEFS_MEAN_RIGHT.png
LGNN5_LGNN5_HEFS_MEAN_SQUARE_ERROR.png
LGNN5_LGNN5_HEFS_MEAN_SQUARE_ERROR_SKILL_SCORE_NORMALIZED.png
LGNN5_LGNN5_HEFS_MEAN_SQUARE_ERROR_SKILL_SCORE.png
LGNN5_LGNN5_HEFS_MEDIAN_ERROR.png
LGNN5_LGNN5_HEFS_MINIMUM_LEFT.png
LGNN5_LGNN5_HEFS_MINIMUM_RIGHT.png
LGNN5_LGNN5_HEFS_PEARSON_CORRELATION_COEFFICIENT.png
LGNN5_LGNN5_HEFS_PEIRCE_SKILL_SCORE.png
LGNN5_LGNN5_HEFS_PROBABILITY_OF_DETECTION.png
LGNN5_LGNN5_HEFS_PROBABILITY_OF_FALSE_DETECTION.png
LGNN5_LGNN5_HEFS_QUANTILE_QUANTILE_DIAGRAM_151200_SECONDS.png
LGNN5_LGNN5_HEFS_RANK_HISTOGRAM_151200_SECONDS.png
LGNN5_LGNN5_HEFS_RELATIVE_OPERATING_CHARACTERISTIC_DIAGRAM_151200_SECONDS.png
LGNN5_LGNN5_HEFS_RELATIVE_OPERATING_CHARACTERISTIC_SCORE.png
LGNN5_LGNN5_HEFS_RELIABILITY_DIAGRAM_151200_SECONDS.png
LGNN5_LGNN5_HEFS_ROOT_MEAN_SQUARE_ERROR_NORMALIZED.png
LGNN5_LGNN5_HEFS_ROOT_MEAN_SQUARE_ERROR.png
LGNN5_LGNN5_HEFS_SAMPLE_SIZE.png
LGNN5_LGNN5_HEFS_SCATTER_PLOT_151200_SECONDS.png
LGNN5_LGNN5_HEFS_STANDARD_DEVIATION_LEFT.png
LGNN5_LGNN5_HEFS_STANDARD_DEVIATION_RIGHT.png
LGNN5_LGNN5_HEFS_SUM_OF_SQUARE_ERROR.png
LGNN5_LGNN5_HEFS_THREAT_SCORE.png
LGNN5_LGNN5_HEFS_VOLUMETRIC_EFFICIENCY.png
pairs.csv.gz
```

The `evaluation.csv` will include everything, so any `.png` file, above, that does not have a corresponding old benchmark CSV was never benchmarked/checked previously.

Also of note, there are file names still using "LEFT" and "RIGHT"; look for the MEAN, MAXIMUM, and MINIMUM files.  *Do we want to fix that for 7.0?* I think so.  I'll create a ticket.

Bottom line, there are a lot of metrics that need checking. *What is the approach we want to use for that checking?* Do I just look at the images, check for "reasonable" results, and then compare with the evaluation.csv to make sure those results are in the CSV? Or do I check the results numerically?

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Created #576 for the "LEFT" and "RIGHT" file name issue.

Hank

**Comment by james-d-brown** [comment]
> Some of the metrics that I need to check are not that simple... at least for me using a spreadsheet. For example, there is a Q-Q diagram, categorical statistics, normalized statistics, and skill scores.

Yeah, there may be some that are harder. It's up to you how far you take it, but I will just note that the checks we did when setting up these tests originally were somewhat comprehensive, mainly in R. But again, the fact we needed to do that may point to a smell, and the 5xx tests really should be regarded as exemplary for future refactoring. But, either way, you will need to compute benchmark statistics from pairs for some of these and a (small) volume of data doesn't really change that.

**Comment by HankHerr-NOAA** [comment]
Okay. I found the "list of expected CSV files in the system test class" and it appears to match what my technique using .png images resulted in. However, that was probably just due to how 100 was declared. I'll make sure to use that list in the system test class moving forward.

An initial check of the "MEAN_LEFT" results appears reasonable, by the way. I used that very simple case as a check of using Excel.

Hank

**Comment by HankHerr-NOAA** [comment]
Oh, and I also see "LEFT AND RIGHT" showing up in the rows of the CSV. For example,

> QME,QINE,,,1,RIGHT,"LGNN5-LGNN5","LGNN5","POINT (103.39 35.34)",0,"REVUELTO CREEK NEAR LOGAN NM","LGNN5","POINT (-103.39360809326172 35.34138870239258)",0,"LGNN5",,,,,-1000000000-01-01T00:00:00Z,+1000000000-12-31T23:59:59.999999999Z,-1000000000-01-01T00:00:00Z,+1000000000-12-31T23:59:59.999999999Z,PT42H,PT42H,PT24H,MEAN,,,,-Infinity,,,,,LEFT AND RIGHT,GREATER,,,,,,,,,ENSEMBLE QUANTILE QUANTILE DIAGRAM,OBSERVED QUANTILES,1974,CMS,-Infinity,Infinity,,201,,,,,,,0.074535

Maybe we need to grep for "left" and "right" in the code base. I'll create a ticket for that when I can get to it. I might not be today.

Hank

**Comment by HankHerr-NOAA** [comment]
> Yeah, I can do that if you haven't already

Please do that, Evan. I am going to really have my hands full with the evaluation CSV checks. 

Hank

**Comment by HankHerr-NOAA** [comment]
Oh, I just confirmed the FALSE ALARM RATIO, not PoFD. Hmmm... Then how is PoFD computed?

Hank

**Comment by HankHerr-NOAA** [comment]
Google's search AI gave me the answer I need:

POFD = False Alarms / (True Negatives + False Alarms). 

FAR = False Alarms / (True Positives + False Alarms). 

Adjusting my spreadsheet accordingly,

Hank

**Comment by james-d-brown** [comment]
Yeah, the difference is the denominator, i.e., observed occurrences vs. forecast occurrences. They are often confused because the PoFD is also known as the false alarm rate.

**Comment by HankHerr-NOAA** [comment]
For the scatter plot, I confirmed the number of rows in the evaluation.csv, checked a few of the points, and then eyeballed a plot created in Excel as compared to the plot output by the WRES. I think that should be enough.

Hank

**Comment by epag** [comment]
Alright, I cleaned up the dirListing for the 900 series tests. Going to run a 900 series test quick locally before pushing those up and then I will look at https://github.com/NOAA-OWP/wres/issues/576 that Hank made

**Comment by james-d-brown** [comment]
By the standard deviation of the observations.

**Comment by HankHerr-NOAA** [comment]
I confirmed the MAE-SS. I went to the code to identify how the skill score is applied: the denominator is the difference between the observed and average observed, while the skill score is computed as (1 - numerator/denominator) where the numerator is the base MAE. Using that, I confirmed the MAE-SS for the "all data" threshold as well as one of the other thresholds, 1.69901. Looks good.

I'll now handle the RMSE-SS per James's comment,

Hank

**Comment by HankHerr-NOAA** [comment]
I've also confirmed the MSE-SS Normalized. I first computed the MSE-SS (Nash-Sutcliffe Efficiency) and then normalized it as, `1/(2-MSE-SS`).

And now I'm left with the really hard ones:

BOX_PLOT_OF_PERCENTAGE_ERRORS
ENSEMBLE_QUANTILE_QUANTILE_DIAGRAM
RANK_HISTOGRAM

I'm going to apply my spreadsheet to the other evaluation results, first, so that I can at least confirm the simpler statistics.

Hank

**Comment by HankHerr-NOAA** [comment]
For scenario102, based on the unit test list of expected files and what was benchmarked before, these are the metrics that need benchmarking:

```
CONTINGENCY_TABLE
ENSEMBLE_QUANTILE_QUANTILE_DIAGRAM_151200_SECONDS
EQUITABLE_THREAT_SCORE
FALSE_ALARM_RATIO
FREQUENCY_BIAS
MAXIMUM
MEAN_ABSOLUTE_ERROR_SKILL_SCORE
MEAN
MEAN_SQUARE_ERROR_SKILL_SCORE_NORMALIZED
MEDIAN_ERROR
MINIMUM
PEIRCE_SKILL_SCORE
PROBABILITY_OF_DETECTION
PROBABILITY_OF_FALSE_DETECTION
ROOT_MEAN_SQUARE_ERROR_NORMALIZED
SCATTER_PLOT_151200_SECONDS
STANDARD_DEVIATION
THREAT_SCORE
```

I'm going to update the list above with `(y)` or `(n)` as I check each statistic.

Hank

**Comment by james-d-brown** [comment]
If we cannot find clear justification (e.g., in the earlier explanation in the test spreadsheet or by identification of qualitatively different assertions), then probably not. Any assertions about graphics are very weak (file names only), except for two scenarios that benchmark the svgs. If the data is tested elsewhere and the declaration is tested elsewhere and the main differences is graphics and there is nothing special about the graphics declaration (no overrides), then we can probably ditch it.

**Comment by HankHerr-NOAA** [comment]
So some of the 102 results were checked and looked good, but, based on James's response, I don't think we need to check the 102 results. 

> If the data is tested elsewhere...

The LGNN5 ESP data is being tested in 103, 105, 107. 

> ...and the declaration is tested elsewhere and the main differences is graphics...

The scenario100 and scenario102 are essentially identical except for HEFS vs ESP and png outputs included in 100. 

> and there is nothing special about the graphics declaration (no overrides)

Scenario100 does not override graphics settings.

> then we can probably ditch it.

I would rather keep scenario100 and ditch scenario102, because I've already done much of the legwork for scenario100. Yes, scenario100 includes graphics, but we can always choose to remove the `png` output format later, since we are already testing `png` in many other tests, if only to confirm that the files are created.

Bottom line, I'd rather we remove scenario102 instead of needing to check the benchmarks.  But, first, let me find the old spreadsheet and see if there was a valid reason for it.

Hank

**Comment by HankHerr-NOAA** [comment]
The spreadsheet is called "System Testing Scenarios" in Google Drive. The reason for 102:

> LGNN5 as 100 using ESP in different .tgz but all files with same header, same file names; This illustrates bug where file hashing required.  Also, includes all metrics but no images, so diagrams will not output.

The comment about diagrams no outputting no longer applies: the diagrams will output to the evaluation CSV. 

I'm not sure to what the "file hashing required" is referring to. Do you recall, James?

Hank

**Comment by HankHerr-NOAA** [comment]
For scenario400, these are the .csvs output as part of the test that were not benchmarked:

```
FALSE_ALARM_RATIO
MAXIMUM
MEAN_ABSOLUTE_ERROR_SKILL_SCORE
MEAN
MEAN_SQUARE_ERROR_SKILL_SCORE_NORMALIZED
MEDIAN_ERROR
MINIMUM
ROOT_MEAN_SQUARE_ERROR_NORMALIZED
STANDARD_DEVIATION
```

Again, I'll mark them with `(y)` or `(n)` as I make progress.

Hank

**Comment by james-d-brown** [comment]
> The spreadsheet is called "System Testing Scenarios" in Google Drive. The reason for 102:
> 
> > LGNN5 as 100 using ESP in different .tgz but all files with same header, same file names; This illustrates bug where file hashing required.  Also, includes all metrics but no images, so diagrams will not output.
> 
> The comment about diagrams no outputting no longer applies: the diagrams will output to the evaluation CSV.
> 
> I'm not sure to what the "file hashing required" is referring to. Do you recall, James?
> 
> Hank

No idea, but you can get more info from the git history, specifically the commit message that added this and the linked ticket.

**Comment by james-d-brown** [comment]
In general, though, I don't favor top-level integration tests to address bugs, rather unit tests.

**Comment by HankHerr-NOAA** [comment]
I confirmed the outputs for scenario400 in the evaluation CSV. I'm going to do a spot check of the images for those metrics. If all looks good, then I think scenario400 is good. 

Hank

**Comment by HankHerr-NOAA** [comment]
The images for the metrics in https://github.com/NOAA-OWP/wres/issues/541#issuecomment-3145037989 look good to me. The values I confirmed for the one pool are present and the general shape appears reasonable. 

I think scenario400 is good to go. Let me research scenario102 a bit more,

Hank

**Comment by HankHerr-NOAA** [comment]
So looking at the spreadsheet further, using `git blame`, and checking the `git log` for `project_config.yml`, I believe scenario102 was originally just created as a step-by-step series of system tests that go from 100 (HEFS evaluation) to 102 (ESP evaluation) to 103 (HEFS evaluation with ESP as a baseline).  In other words, we could look at the output from 100 and 102 to check the skill score output from 103. I was just building up these tests cases in order to exercise the WRES, not necessarily to create a set of unique system tests that touch on as many features of the WRES as possible. 

The reference to the bug was almost certainly added later, but its still not clear to me to what it is referring. I'm going to eat lunch and then do a bit more research. After that, I'm going to have to determine how to handle the last three metrics for scenario100, noted in https://github.com/NOAA-OWP/wres/issues/541#issuecomment-3144882103.

Hank

**Comment by HankHerr-NOAA** [comment]
Maybe the formula I'm using for quantiles is off. I thought he probability was `i/N+1` where `i` is the rank, 1,...,N. However, I'm seeing different results for the ensemble quantile quantile diagram, so perhaps I'm just off. Let me double check with the code,

Hank

**Comment by HankHerr-NOAA** [comment]
Just confirming, but the observed quantiles are pulled directly from the pairs, and not from the complete observed data, right? In other words, does it include observations that are not paired?

I ask, because the smallest quantiles for member 1952 found in the evaluation CSV has observed value `0.000743`. That value does not exist in `sorted_pairs.csv`. 

Hank

**Comment by HankHerr-NOAA** [comment]
Okay... I see this at the top of `EnsembleQuantileQuantileDiagram.java`:

>  Uses as many quantiles as the smaller of the number of order statistics and the {@link #DEFAULT_PROBABILITY_COUNT}.

The value of `DEFAULT_PROBABILITY_COUNT` is 100. I'm pretty sure I'm seeing a linearly interpolate value corresponding to the 0.01 quantile. Let me double check,

Hank

**Comment by james-d-brown** [comment]
See `Slicer::getQuantileFunction`, which explains it. This returns a function that computes a quantile from a probability. A probability is supplied. Yes, we use a discrete set of probabilities, otherwise the diagram is up to the size of the raw data, aka the empirical quantiles. But the method is important so see that function for docs.

**Comment by james-d-brown** [comment]
```
    /**
     * Returns a function to compute a value from the sorted array that corresponds to the input non-exceedence 
     * probability. This method produces undefined results if the input array is unsorted. Corresponds to 
     * method 6 in the R function, <code>quantile{stats}</code>. This is largely equivalent to the
     * <code>PERCENTILE.EXC</code> function in Microsoft Excel, but the latter cannot compute the bounds or values
     * close to the bounds: <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html">https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html</a>.
     * Also see: <a href=
     * "https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample">https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample</a>.
     */
```

Which may answer your earlier question...

**Comment by james-d-brown** [comment]
Can you read those docs again? I think it answers your question, which is what I was alluding to...

**Comment by HankHerr-NOAA** [comment]
I'm sorry, but I'm not sure what you expect me to see. You might need to spoon feed me the answer.

I assume you are directing me to the links you provide in the `Slicer.java` for `getQuantileFunction`, which you note above. Following the link,

https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html

I see this:

> The smallest observation corresponds to a probability of 0 and the largest to a probability of 1.

My largest percentage error is `188831.9111`, which should be returned for `BOX PLOT OF PERCENTAGE ERRORS,PROBABILITY,ENSEMBLE MEAN,PROBABILITY` of `1.000000`. However, the WRES returns a value for `BOX PLOT OF PERCENTAGE ERRORS,ERROR PERCENT OF VERIFYING VALUE,ENSEMBLE MEAN,PERCENT` of  `188834.545174`. 

Continuing through the R documentation, I see no further references that could result in a different conclusion: if a 1.0 probability is passed in, then the largest value (percentage error) should be returned, and, from my computations, that should be `188831.9111`. 

I suppose I could be computing the percentage error incorrectly, but I see this in `BoxPlotPercentageError.java`:

```java
        double[] sortedPercentageErrors =
                pool.get()
                    .stream()
                    .mapToDouble( a -> ( ( a.getRight() - a.getLeft() ) / a.getLeft() ) * 100 )
                    .sorted()
                    .toArray();
```

Its a straight forward, `((fcst mean - obs)/obs) x 100%` computation, which I did in Excel.  Again, that gives me a seemingly different value for the largest percentage error than, apparently, the WRES.

Hank

**Comment by HankHerr-NOAA** [comment]
I'm very close to confirming the "all data" rank histogram in Excel. However, there are a few values at the upper end that are differing, I'm still investigating,

Hank

**Comment by HankHerr-NOAA** [comment]
I confirmed the rank histogram after fixing an error in my spreadsheet. Yay!

Hank

**Comment by HankHerr-NOAA** [comment]
Bottom line, with one exception (which I'm still investigating), I've confirmed the benchmarks for scenario100 and scenario400, while I plan to remove scenario102. 

The 900 series just needed an update to the expected output files, which Evan tackled.

I have some other tasks to tackle, including the wonderful 5-accomplishments email, but plan to return after and finish out my day in the hopes that I can identify the box plot of percentage errors issue documented above.

Hank

**Comment by james-d-brown** [comment]
OK, perhaps I misunderstood what you were saying. Bottom line, the WRES adopts method 6 in the R documentation (`type=6`), which is NOT the same as `PERCENTILE.EXC` in the limits, which returns undefined. But, yes, it should return the empirical limits for the upper and lower bounds, and it does do that because it is unit tested - see the `SlicerTest::testGetQuantileFromProbability` for evidence.

I guess your calculation of the percentages is slightly different for whatever reason and that is probably the thing to focus on...

**Comment by HankHerr-NOAA** [comment]
Evan offered to remove scenario102, since he is already working with the scenario code. With that change, this ticket should be resolved. 

Thanks, Evan!

Hank

**Comment by HankHerr-NOAA** [comment]
I don't know if this is appropriate, but, for future reference, here is the Excel spreadsheet I used to do my checking (rather crude, but might be useful if something like this has to be done again in the future):

[sorted_pairs_scenario100.xlsx](https://github.com/user-attachments/files/21554054/sorted_pairs_scenario100.xlsx)

In general, I tested the results for a single pool, and, if stats were to be computed for members (e.g., ensemble q-q diagram), then I only computed it for one member. For the rank histogram, I only confirmed the "all data" threshold. Admittedly, that was a bit of a cop out, but there is no particular reason to believe that the computation wouldn't work for a threshold (its the same code, just a different set of data), and, frankly, I'm running out of time.  

That's it for me. Have a great weekend!

Hank

**Comment by epag** [comment]
Or wait, was scenario100 the one we wanted to delete? I cant remember, let me check that too haha

**Comment by epag** [comment]
> Or wait, was scenario100 the one we wanted to delete? I cant remember, let me check that too haha

Nope that was scenario102, let me see why scenario100 is failing, that one has a huge output

**Comment by james-d-brown** [comment]
I have pushed, which is why you can see 7f6e62c6ac3c2e7a4b0bd07f5fe5fb2a64556daf.

You will need to git fetch before you can cherry pick to the required branch.

**Comment by james-d-brown** [comment]
:)
